### ISSUE TITLE
Public projects' data is only accessible to Project Users

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1571] opened 2017-06-09 12:27 UTC
### Steps to reproduce the error

1. Access to the platform as a anonymous user, registered user (but not being a member of the org) or public user 
2. Try to access to a public project (for instance, [this one](https://platform-staging.cadasta.org/organizations/david-org/projects/katrina-and-david-testing/))
3. When you try to open a location you get a permissions error message

### Actual behavior

See above

### Expected behavior

Public projects' data (including entity attributes) should be accessible to Public Users, Registered Users, and Anonymous users. 

Something to take into account when removing tutelary (cc @bjohare)

**Comment by oliverroick** [comment] 2017-06-12 07:42
This is not a bug, this is expected behaviour. If we want to change the behaviour we should add it to the permissions table in [DR 0008](https://github.com/Cadasta/decision-records/pull/8). 

I think, we can close the ticket when the required changes are added to the permissions table.

**Comment by oliverroick** [comment] 2018-02-16 09:59
Expected under the current implementation. Closing

**Closed by oliverroick** 2018-02-16 09:59 UTC
Labels: permissions
