### ISSUE TITLE
Roboto font not importing correctly

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#260] opened 2016-06-22 22:41 UTC
Roboto font is not importing correctly or being used correctly on Oliver's machine.

**Comment by oliverroick** [comment] 2016-06-28 08:54
I have merged PR #275 but the problem is still not fixed. 

I have checked this on various browsers: 

- Chome 51.0.2704.106 (64-bit) (even cleared my complete cache)
- Safari 9.1.1 (11601.6.17)
- Firefox 47.0

It seems that  it works in the wherever Roboto regular is applied (I can’t tell for sure as I’m not good at telling fonts apart). For the headlines _Roboto Condensed_ is used, that's when the browser falls back to Helvetica on my machine. Maybe Roboto Condesed is not installed with the web fonts?

**Comment by clash99** [comment] 2016-06-28 13:17
Thanks for the info - I will check it out.

**Comment by clash99** [comment] 2016-06-29 13:43
@oliverroick - You were totally right...  fixing it in my resources branch now.  Thanks!

**Comment by clash99** [comment] 2016-06-29 13:43
Adding Roboto Condensed and removing Steelfish fonts since we aren't using them.

**Comment by clash99** [comment] 2016-06-30 18:07
Kate confirmed this is working correctly with latest merge.  Marking complete.

**Closed** 2016-06-30 18:07 UTC
Labels: bug, ui
