### ISSUE TITLE
Add geospatial search API for locations (spatial units)

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#238] opened 2016-06-13 09:28 UTC
Currently there is no API to search for locations (spatial units) given some geospatial criteria, like a bounding box or an administrative boundary, and across projects. There will certainly be use cases for this kind of search (ex. "Give me all parcels located within Lagos, Nigeria in all of my organization's projects.").

I think this isn't needed for v0.1, though.

**Comment by ian-ross** [comment] 2016-06-13 09:35
Duplicate of #208

**Closed by ian-ross** 2016-06-13 09:35 UTC
Labels: enhancement
