### ISSUE TITLE
Public user is able to view sidebar in a project

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1460] opened 2017-05-02 20:31 UTC
### Steps to reproduce the error

Login as a public user of a project.  The user should not be able to view the left subnav of a project. (Original development part of ﻿#942)

### Actual behavior

I can view the project subnav.  It seems as though `is_project_member` is not working as expected.

### Expected behavior

Public user shouldn't be able to view the project subnav.

**ON STAGING, logged in as public user:**
<img width="1440" alt="screenshot 2017-05-02 15 19 15" src="https://cloud.githubusercontent.com/assets/1119621/25637473/bf469fa2-2f4a-11e7-95df-1e4a9ff07258.png">

<img width="1438" alt="screenshot 2017-05-02 15 18 12" src="https://cloud.githubusercontent.com/assets/1119621/25639483/b3552ad6-2f51-11e7-9c8f-537d1fcebcf8.png">

**Comment by clash99** [comment] 2017-05-02 21:00
I can't recreate this locally.  When I'm logged in as a public user for a project, the subnav is hidden.  (You can see is_project_member flag behind the org name above project heading) 

<img width="1436" alt="screenshot 2017-05-02 15 58 22" src="https://cloud.githubusercontent.com/assets/1119621/25639123/5a2720f0-2f50-11e7-9564-e58f580e74ef.png">

**Comment by clash99** [comment] 2017-05-02 21:05
I created a new org and a new project and added a new public user on staging and it seems to be correctly hiding the left subnav.

**Comment by seav** [comment] 2017-05-03 01:30
I have a hunch that the public user still has a lingering `ProjectRole` object in the database which is why `is_project_member` is not false.

**Comment by amplifi** [comment] 2017-05-03 07:17
In the staging database, user `clash33` has only Public User permissions, applied at `2017-05-02 19:36:36.149993+00`. There are no other historical or 'lingering' roles for this user. Public User permissions in staging are as in `cadasta/config/permissions`.

There are inconsistencies in the codebase regarding permissions. According to comments on #942, `is_project_member` should resolve as `True` if the user is a superuser, org admin, project manager, data collector, or public user. However, [is_project_member](https://github.com/Cadasta/cadasta-platform/blob/bc33ec47831432b7b5e5a324fbbd1fd09d2d1f26/cadasta/organization/views/mixins.py#L118) actually returns `True` if the user is an admin or has a defined `ProjectRole` as returned by [get_prj_role](https://github.com/Cadasta/cadasta-platform/blob/bc33ec47831432b7b5e5a324fbbd1fd09d2d1f26/cadasta/organization/views/mixins.py#L72). This seems to anticipate that only Project Users and above will have explicitly assigned roles in the database, but this isn't the case. Public Users also have a defined `ProjectRole`; only anonymous users lack an explicit `ProjectRole`.

The existence of explicitly defined roles for Public Users also seems to contradict the underlying table schema for [ProjectRole](https://github.com/Cadasta/cadasta-platform/blob/1ebd1e62a9d7bcd61cd1b1bd982c2fe66d624b09/cadasta/organization/migrations/0001_initial.py#L165). The use of Django charfield `choices` here looks like an intent to restrict the stored `role` values in the database to exclude Public User (`Pb`), but that doesn't function the same as defining a foreign key constraint.

**Comment by dpalomino** [comment] 2017-05-03 10:22
Hey @clash99. I have just tested this issue and it seems to be working fine for me with a new public user in an existing organization and project: 
https://platform-staging.cadasta.org/organizations/david-new-org/projects/hfh-legal-land-desk-01/

Left subnav is properly hidden with user dpalomino-6 (dpalomino+testing6@cadasta.org).

**Comment by amplifi** [comment] 2017-05-03 10:48
User `dpalomino-6` on staging has no explicitly assigned role(s) in the database. There's definitely a bug involving the creation of `ProjectRole` objects for Public User roles, if the intended behavior is for Public Users to have no corresponding `ProjectRole` object. (Otherwise, if Public Users are intended to have `ProjectRole` objects, there is a bug whereby this object is only created via certain pathways, and `is_project_member` should be modified along with the data model.)

**Comment by wonderchook** [comment] 2017-05-03 21:46
@dpalomino I think we need to you to clarify what a public user who is a member of an org is able to do. 

My understanding is they were supposed to be the same as a public user who is not a member of an organization. That way orgs can have someone in their org, but also restrict access of their members to specific projects. Otherwise the public user role doesn't have a purpose.

**Comment by dpalomino** [comment] 2017-05-04 10:25
Thanks @wonderchook, @clash99. I'm trying to draft my understanding for public users permissions re subnav and geometries: 

Public users that are members of the org (for private projects): 
- Left subnav: hidden (current behaviour in staging)
- Spatial Units geometries: shown (also current behaviour in staging)
- General overview stats: shown (current behaviour in staging)

Public users that are **not** members of the org (for private projects): 
- Current behaviour: user get a permission denied message when trying to access to the project

In my opinion public users that are not member of the organization should not access to any information from the project (I think all of us would agree on this). 

So the question is if public users that are members of the organization should have access to private projects to see 1) spatial units geometries; 2) overview stats. But not accessing to any information regarding entity details etc. In my opinion I think it could be fine to add some little permissions (such as these, stats and geometries) for public users that are members of the org compared to those not member of the org. I think orgs are fine to share this kind of general information with all their users... but happy to hear more opinions :-) 

On a side note, I think it'd be more clarifying if we add a "Default" (i.e. Public User) column in the permissions assignment's table in the wiki: 
https://devwiki.corp.cadasta.org/Permissioning%20policies#permission-assignments

If you are ok with this I can add it to my to-do list. 

I think (correct me if I'm wrong) "project.view_private" is intended to specify if the user can view project stats and geometries. I think it'd be good to split these in two so we can define separately if public users members of the org can see stats and/or boundaries. Do you agree?

**Comment by wonderchook** [comment] 2017-05-04 12:59
@dpalomino are you saying public users not part of the org can't see anything on a public project? I don't think that makes sense. A public project someone not signed in should be able to go to the project overview page.

**Comment by dpalomino** [comment] 2017-05-04 13:38
> @dpalomino are you saying public users not part of the org can't see anything on a public project? I don't think that makes sense. A public project someone not signed in should be able to go to the project overview page.

Hi @wonderchook. No, I was referring only to private projects.

**Comment by dpalomino** [comment] 2017-05-11 16:15
Not consistent behavior. To be restested after permission redesign.

**Comment by dpalomino** [comment] 2017-05-24 16:26
There is a PR ongoing that should fix the issue, #1515

**Comment by dpalomino** [comment] 2017-06-06 11:54
PR was already merged, closing issue.

**Closed by dpalomino** 2017-06-06 11:54 UTC
Labels: bug, permissions, priority: medium
