### ISSUE TITLE
Typo in flash message after incorrect login.

### ISSUE THREAD

**Issue by rishabhiitbhu** [Cadasta/cadasta-platform#1308] opened 2017-03-16 05:55 UTC
### Steps to reproduce the error

- Login with wrong credentials.

### Actual behavior

![screenshot from 2017-03-16 10-57-17](https://cloud.githubusercontent.com/assets/17473589/23983579/ec378fb0-0a3a-11e7-942e-4f4578547e96.png)

### Expected behavior

![screenshot from 2017-03-16 11-24-11](https://cloud.githubusercontent.com/assets/17473589/23983629/300e4e2c-0a3b-11e7-9973-a212d663e05b.png)

**Comment by rishabhiitbhu** [comment] 2017-03-16 06:01
I would like to take up this issue.

### Approach

- I have found that this message is created at `LoginForm` class of `allauth.account.forms.py` [link](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L87)
- I will create a new `LoginForm` class in `accounts/forms.py` inheriting `LoginForm` of  `allauth.account.forms.py` and overwrite the message.
- Edit `ALLAUTH_FORMS` by adding new key `login` with value as `accounts.forms.LoginForm`  `config/settings/default.py` [link](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/settings/default.py#L161) 
- Add new test class `LoginFormTest` in `accounts/tests/test_forms.py` and add new test method to assert this change.

**Comment by wonderchook** [comment] 2017-03-16 21:07
I think the text should be "The username and/or password you specified are not correct." 

Other than that you can take this up.

**Comment by rishabhiitbhu** [comment] 2017-03-17 07:10
@wonderchook thanks for your suggestion. I have applied your suggested changes in my PR.

**Comment by seav** [comment] 2017-03-21 13:25
So I've looked into this and this defect is caused by a mismatch between the form field label and the allowed authentication method.

In our login page template, we use the label "Username" for the login field: https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/allauth/account/login.html#L48

However, we have specified that the user can use either their username or email address when logging in: https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/settings/default.py#L136

In fact, you can log in using your email address even though the field is labeled "Username".

So the question is, do we want users to be able to log in using only their username or also using their email address? If it's the former, then we need to change our setting to `username` instead of `username_email`. If it's the latter, then we need to update our template label to "Username or e-mail" (to match allauth) instead of just "Username".

**Comment by rishabhiitbhu** [comment] 2017-03-21 14:39
@seav thanks for looking into it. 
I raised an issue #1319 which intends to add login with email too as it will be helpful if user forget his/her username. So `username_email` in [here](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/config/settings/default.py#L136) is good.
  
Changing label "Username" to "Username or e-mail" will change the lable of text input field, which is correc but the login error message will remain same, as error message for incorrect login for `username_email` is [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L86) and it is created [here](https://github.com/pennersr/django-allauth/blob/master/allauth/account/forms.py#L161)

**Comment by seav** [comment] 2017-03-21 15:10
The error message is the default provided by django-allauth. I don't think overriding it without a good reason is OK. If the label is now "Username or e-mail", then the error message now makes more sense because the user will associate "login" with either the username or the email address that they provided.

**Comment by rishabhiitbhu** [comment] 2017-03-21 15:12
@seav thanks, I got it.
Should I update lable [here](https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/templates/allauth/account/login.html#L48) and update my PR, reverting all other changes?

**Comment by oliverroick** [comment] 2017-03-21 17:06
There's issue #1323 and PR #1324 to address the label issue. I think we should close this issue, plus the corresponding PR.

**Comment by rishabhiitbhu** [comment] 2017-03-22 05:55
@seav I think we can make the login error message more explicit. The error message is created by `clean` method of `allauth.accout.LoginForm` class.  I inherited the class in `cadasta/accounts/forms.py` and did some work [link](https://github.com/rishabhiitbhu/cadasta-platform/blob/logintest/cadasta/accounts/forms.py#L66) to make this error message truly explicit.
We allow "@" in usernames while registrations if we could restrict that, we could make this work.
Please have a look.

**Comment by oliverroick** [comment] 2017-03-22 07:57
@rishabhiitbhu Thank you for looking into this. I don't think that adding your solution will add much benefit, though. Users know which login method they used, so the standard error message is sufficient (that's obviously an assumption, we haven't run any user tests on this). Adding 22 lines of code only to change one word in an error message adds too much complexity for a very minor problem. I we add it we have to maintain in the future and it might cause problems when we want to update `django-allauth`.

**Comment by rishabhiitbhu** [comment] 2017-03-22 07:59
@oliverroick I got it. I think this issue should be closed.

**Closed** 2017-03-22 16:52 UTC
Labels: bug, priority: low, ui/ux
