### ISSUE TITLE
Staging: Date is Broken

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1718] opened 2017-08-15 14:17 UTC
### Steps to reproduce the error

On the platform, date picker is not working when you try to fill it out.

### Actual behavior

<img width="315" alt="screen shot 2017-08-15 at 7 34 19 am" src="https://user-images.githubusercontent.com/25337622/29319520-8ad6dd4c-8191-11e7-967f-571a443443cc.png">
<img width="370" alt="screen shot 2017-08-15 at 7 26 02 am" src="https://user-images.githubusercontent.com/25337622/29319526-8ed185be-8191-11e7-9f80-3700d9e32c69.png">

**Comment by clash99** [comment] 2017-08-15 15:40
I can't recreate this.  From your screenshot it looks the css/js is not loading in a timely manner to display numbers as days in month div.  

I'll look into it more but this is what I'm seeing when adding a party with a date of birth:

![screenshot 2017-08-15 10 13 45](https://user-images.githubusercontent.com/1119621/29322403-f5bf7608-81a2-11e7-8c0f-f036d8725a41.png)

**Comment by laura-barluzzi** [comment] 2017-08-22 18:20
@clash99 is it normal I don't see this field at all in staging currently?

**Comment by clash99** [comment] 2017-08-22 18:53
@laura-barluzzi  It is based on the fields you have in your project questionnaire. [This questionnaire](https://docs.google.com/spreadsheets/d/1iORFg75ofq-QzLB5x-WvuggEZN6JaE0iS6yqc7dE1Y0/pub?output=xlsx) has dob for an individual party.

**Comment by SteadyCadence** [comment] 2017-08-22 20:10
Yea, it seems to work fine on other questionnaires.  I'll have to find which questionnaire that was that I uploaded to see which one it was.

**Comment by dpalomino** [comment] 2017-08-24 11:59
I think we can close this for now, as we were not able to reproduce it with other questionnaires. Please reopen if needed.

**Closed by dpalomino** 2017-08-24 11:59 UTC
Labels: bug
