### ISSUE TITLE
Data Downloads

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#220] opened 2016-06-06 18:16 UTC
# Summary
Project Managers and Organizational Admins need to be able to bulk download data from a project. For version .01 xls and shp will be required for download.

# Links to requirements and functional testing script
* [Requirements](https://devwiki.corp.cadasta.org/Data%20Download)

# Acceptance criteria

# Task list (including tests)

**Comment by seav** [comment] 2016-06-30 16:26
Is the download action intended to be blocking (the webpage hangs until the download starts)? Or do we do an asynchronous style, like the creation of an atlas in Field Papers?

**Comment by seav** [comment] 2016-06-30 16:43
I assume that we will be using django-shapes to export our locations as shape files?
https://pypi.python.org/pypi/django-shapes

The problem is that this package was released in 2010 so it might only be compatible with Python 2 or an older version of Django.

**Comment by wonderchook** [comment] 2016-06-30 16:44
We were thinking of doing this in phases. Phase one would be either csv or excel files to start. Phase two would include shape. 

I don't think we would initially do this asynchronous style since that is more complicated.

**Comment by clash99** [comment] 2016-07-05 20:40
Updated wireframe for data download modal:  
![2 2 1 5 location detail_ location - download data modal](https://cloud.githubusercontent.com/assets/1119621/16599178/c1757e4a-42c6-11e6-97ed-7bcec069a71d.png)

**Closed** 2016-07-07 17:36 UTC
Labels: high priority
