### ISSUE TITLE
Project locations no longer displaying on any of the project pages

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#964] opened 2016-12-02 15:03 UTC
### Steps to reproduce the error
(based on the latest version of master)
Go to any project page that has spatial units.

### Actual behavior
The full global map is displayed with no polygons on it.

### Expected behavior
Project location polygons displayed.

**Comment by oliverroick** [comment] 2016-12-02 15:07
Possible duplicate of #949? #949 is fixed in #951.

**Comment by wonderchook** [comment] 2016-12-14 00:33
@linzjax can you confirm this is fixed?

**Comment by linzjax** [comment] 2016-12-14 15:15
Confirmed 👍

**Closed** 2016-12-14 16:04 UTC
Labels: bug
