### ISSUE TITLE
Newly added locations don't appear on the map

### ISSUE THREAD

**Issue by seav** [Cadasta/cadasta-platform#1222] opened 2017-03-07 14:44 UTC
### Steps to reproduce the error
1. In a project on staging (v1.7.0-alpha.3 release), add a new location.
2. Go to the project's Overview tab.

### Actual behavior
The new location is missing from the map.

### Expected behavior
The new location should be visible on the map.

### Remarks
I have a feeling that this is caused by aggressive caching due to #1170. I am guessing that `application/json` should also not be cached similar to `text/html`.

**Comment by oliverroick** [comment] 2017-03-07 15:03
I can't reproduce this where I am; tried to add four new locations, all of them were showing up on the map immediately.

**Comment by bjohare** [comment] 2017-03-07 15:04
I can't reproduce this either.

**Comment by seav** [comment] 2017-03-07 15:24
This is either a problem with my network (ISP), OS, or Firefox. Using Chromium, I am able to reproduce this bug but force-reloading the page shows the new location. With Firefox, force-reloading the page does not work; I need to clear the cache for it to work.

**Comment by amplifi** [comment] 2017-03-07 16:50
Same happened for @clash99 in #1229 -- looks like more than a local issue.

**Comment by clash99** [comment] 2017-03-07 16:52
Clearing cache was only way for me to see new locations.

**Comment by amplifi** [comment] 2017-03-07 17:04
`application/json` was already being cached at the same setting as part of the default nginx config prior to this release -- that's why some people had to force refresh or clear their cache after deployments to get the latest js versions.

**Comment by seav** [comment] 2017-03-07 17:31
I'm wondering if `application/json` should also be included here: https://github.com/Cadasta/cadasta-platform/blob/master/provision/roles/webserver/production/templates/nginx-production#L5-L11

**Comment by amplifi** [comment] 2017-03-07 17:35
@seav No. Including `application/json` in that block will result in json being cached by the user's local browser. We don't want that. If this issue were due to caching settings, it would: be reproducible by all of us, reoccur on each subsequent attempt after clearing the cache, not occur with caching disabled, and not occur via the API URL. Those conditions don't hold here.

**Comment by seav** [comment] 2017-03-07 17:46
So the `default 24h` line is not applied when `$sent_http_content_type` = `application/json`?

**Comment by amplifi** [comment] 2017-03-07 17:50
@seav No. `application/json` is not being cached under the current config.

**Comment by dpalomino** [comment] 2017-03-07 19:27
I cannot reproduce either.

**Comment by clash99** [comment] 2017-03-08 16:06
Update: Tried to recreate yesterday's bug and its working correctly now.

**Comment by dpalomino** [comment] 2017-03-08 17:01
Then I think we can close this and reopen if happens again...

**Closed by dpalomino** 2017-03-08 17:01 UTC
Labels: bug
