### ISSUE TITLE
Changing Language (on Registration) Does not completely translate page

### ISSUE THREAD

**Issue by MappingKat** [Cadasta/cadasta-platform#1901] opened 2017-11-16 01:48 UTC
### Steps to reproduce the error

1. Register User with language, such as "French"
2. Get taken to the "Verfication page" and observe lots of english on that page

### Actual behavior
The page that the user is taken to has a lot of english... 
<img width="623" alt="screen shot 2017-11-15 at 6 44 37 pm" src="https://user-images.githubusercontent.com/1077436/32869686-957e04ae-ca35-11e7-8202-42f60e9d8d98.png">

### Expected behavior

Expect whole page to be in the chosen language.

**Comment by oliverroick** [comment] 2017-11-16 12:03
This is nothing we can fix quickly. The problem is that the translations are not updated frequently on Transifex. French is missing roughly 25% of the translations at the moment. Unless we find someone who can translate the missing strings for us, this won't change.

**Comment by oliverroick** [comment] 2018-01-23 11:40
Closing this since it's not a bug in the platform.

**Closed by oliverroick** 2018-01-23 11:40 UTC
Labels: bug, priority: medium, ui/ux
