### ISSUE TITLE
Form Upload :: Form Does not show up on GeoODK (staging)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1253] opened 2017-03-09 05:04 UTC
### Steps to reproduce the error

1. Create New project and upload attached questionnaire to project.
2. View a successful import.  Add a location, party/relationship, etc
3. Go to `/collect` and see form has not been submitted. Sign in to GeoODk, refresh form management-- form does not show up.

[arc-questionaire-v0.1.xlsx](https://github.com/Cadasta/cadasta-platform/files/829813/arc-questionaire-v0.1.xlsx)

**Comment by dpalomino** [comment] 2017-03-09 11:52
Hi @SteadyCadence! Maybe we can review when you have a moment. I've not seen this issue with other forms, I think it could be due to some format issues with the form.

**Comment by dpalomino** [comment] 2017-03-09 19:24
confirmed with @SteadyCadence that was due the form, we can close this issue :)

**Closed by dpalomino** 2017-03-09 19:24 UTC
Labels: needs investigation
