### ISSUE TITLE
Extra scrollbars in dashboard map UI

### ISSUE THREAD

**Issue by IvanSanchez** [Cadasta/cadasta-platform#449] opened 2016-07-14 17:11 UTC
![screenshot1](https://cloud.githubusercontent.com/assets/1125786/16848591/c37e09a0-49f6-11e6-9cde-4f5e154d6aa7.png)

Extra scrollbars appear when browsing the map. Problem is not specific to a single browser (can be reproduced at least with recent firefox and chrome).

**Comment by seav** [comment] 2016-07-14 18:33
Duplicate of #249

**Closed by seav** 2016-07-14 18:33 UTC
