### ISSUE TITLE
Export :: Error when export "All Data" on project with around 100 locations

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1160] opened 2017-02-24 18:19 UTC
### Steps to reproduce the error

1. Head to https://demo.cadasta.org/organizations/cadasta-demo-organization/projects/urban-infrastructure-demo/download/
2. Click "All data" option
3. Get taken to an error page

### Actual behavior

It looks like this is the error that pops up in the logs:
```IndexError at /organizations/cadasta-demo-organization/projects/urban-infrastructure-demo/download/ tuple index out of range```

### Expected behavior

To be able to export all data from the project.

**Comment by dpalomino** [comment] 2017-02-28 00:39
I think it is a duplicate of #1098, which is already fixed but still not deployed to production.

**Closed by dpalomino** 2017-02-28 00:39 UTC
