### ISSUE TITLE
Delay between creating locations and viewing them on map or overview tab

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1229] opened 2017-03-07 16:48 UTC
### Steps to reproduce the error

I've created a location in a project but can't view it on the overview tab or the map tab. 

### Actual behavior

Project appears empty on both overview and map tab although the stats on the map tab says 1 location.

### Expected behavior

I would expect to see my location on the map where I can select it to view details.  If the project stats show the # of locations, I would expect to see that # reflected on the map.

I waited several minutes and it didn't appear on refresh.  I cleared my cache and then it did appear.  Don't know if its a cache issue or a delay.

Video:  https://screencast.com/t/wuawIhysp

**Comment by amplifi** [comment] 2017-03-07 16:50
Duplicate of #1222

**Closed by amplifi** 2017-03-07 16:50 UTC
Labels: bug

**Comment by clash99** [comment] 2017-03-07 16:53
thanks @amplifi - sorry i missed the duplicate!
