### ISSUE TITLE
Projects with large numbers of locations are unresponsive

### ISSUE THREAD

**Issue by bjohare** [Cadasta/cadasta-platform#801] opened 2016-10-06 14:26 UTC
### The issue

Projects that have large numbers of records, e.g, by having 1000's of records imported, are unresponsive. Projects with an excess of 4200 `SpatialUnits` take two minutes for the Project Dashboard to render. This is caused by loading `geojson` for all the project locations into the dashboard template context. 
### Expected behavior

The project dashboard should render in an acceptable timeframe regardless of how many locations the project holds.

**Comment by wonderchook** [comment] 2016-10-08 11:42
We need to look at the various options for dealing with this:

- Using server side clustering so we aren't loading all the GeoJSON at once
- Serving point data until users are zoomed in to a certain extent 
- Possibly serving vector tiles
- Using a provider such as CartoDB or Mapbox to serve the data for us.

**Comment by seav** [comment] 2016-10-08 19:09
We are probably doing something very inefficient. I have no trouble loading and displaying 73215 nodes and 5285 ways as a result of an Overpass Turbo query for OSM data. (For those unfamiliar, Overpass API is like SQL for the OpenStreetMap database and Overpass Turbo is the most popular GUI for this API.)

**Comment by wonderchook** [comment] 2016-10-09 07:10
So it looks like the issue is beyond the map now that I've actually looked at it. Since loading a project with many records is an issue. Thanks for the test @seav

**Comment by ian-ross** [comment] 2016-10-10 07:31
@seav We've not spent **any** time on optimisation work because of what we understood to be the timescale for data acquisition.  We were planning to do optimisation work gradually over the next six months or so.  We are probably doing *dozens* of inefficient things.

**Comment by wonderchook** [comment] 2016-10-14 12:37
#824 is related

**Comment by dpalomino** [comment] 2016-11-02 17:14
All "easy" optimizations were already done and difference in performance is very significant (thanks a lot to all for this!). For larger numbers (around 50K) we will require much more effort. 

We will open new issues for further optimizations. For now we can close this.

**Closed by dpalomino** 2016-11-02 17:14 UTC
Labels: bug, high priority, needs investigation
