### ISSUE TITLE
Work in Progress :: Shapefile Export Issues

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-platform#1431] opened 2017-04-26 18:37 UTC
### Steps to reproduce the error

1. Go to a project with data and export to a shapefile. 

### Notes
- [ ] project extent is exported in the shapefile (http://arcg.is/zrS5O)
- [ ] only ids are included in the attribute table of the polygon (ihttps://demo.cadasta.org/organizations/itc-university-of-twente/projects/itc-customary-rights/)

**Comment by alukach** [comment] 2017-05-05 04:54
@SteadyCadence Any updates on this?

**Comment by wonderchook** [comment] 2017-05-05 12:58
@SteadyCadence I think this is working as designed. (Not the project extent part that is a bug). Due to the limitation on shapefile column names they are exported in a different file and joined. @oliverroick is my memory correct?

**Comment by oliverroick** [comment] 2017-05-05 15:49
Yes, that's correct. We figured it was too much work to work around the limitations of shapefile (field names, certain types), so you get a shape with all the geometries and IDs and a CSV with all the data. 

It might be worth replacing SHP with Geopackage, it's widely supported now and addresses the shortcomings of shape file.

**Comment by dpalomino** [comment] 2017-05-11 16:44
To be followed in #1498, closing this issue.

**Closed by dpalomino** 2017-05-11 16:44 UTC
Labels: bug, priority: medium
