### ISSUE TITLE
Project Location - "Submit Valid Date" with no info on how to format date

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#576] opened 2016-08-21 21:41 UTC
### Steps to reproduce the error

* Try to create a new project location
* Enter a date that the project location was obtained
* Get error "Enter a valid date"

### Actual behavior

I tried to enter a date formatted like:
August 21, 2016

Then like:
08.21.2016

And then finally tried:
08/21.2016

It worked, but it took 3 tries

### Expected behavior

I expected that I'd get a note telling me what format was correct along with my error message, or some kind of hint for how to format the date.

**Comment by wonderchook** [comment] 2016-08-22 15:05
We should add a date picker to fields to date fields.

**Comment by seav** [comment] 2016-08-23 16:17
Duplicate of #461?

**Comment by wonderchook** [comment] 2016-08-23 16:45
Oops, yes closing as a duplicate

**Closed by wonderchook** 2016-08-23 16:45 UTC
Labels: enhancement
