### ISSUE TITLE
Some specific formats for GPX files are failing (500 error) 

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#1350] opened 2017-03-27 22:55 UTC
### Steps to reproduce the error

Have .gpx (or a .xml made with a .gpx)
Go to attach it as a resource to a project

### Actual behavior

Get platform error

### Expected behavior

The file should be attached to the project. 

//

Specific files are attached below:

[gpx-xml.zip](https://github.com/Cadasta/cadasta-platform/files/874017/gpx-xml.zip)

**Comment by dpalomino** [comment] 2017-03-29 16:10
Need more testing to find out what the root cause really is.

**Comment by clash99** [comment] 2017-04-07 22:13
WIP - Can be uploaded if all points are contained in same track segment.  Blows up with multiple track segment.s

**Comment by dpalomino** [comment] 2017-04-10 08:32
Thanks for testing @clash99! @bjohare, do you think this would be something difficult to fix?

**Comment by oliverroick** [comment] 2017-04-10 14:53
Here's the corresponding [error log](https://opbeat.com/cadasta/platform-staging/errors/131/)

**Comment by dpalomino** [comment] 2017-04-12 16:34
We need to do some more research to know if this is a valid format, and how partner managed to have this GPX file. GPX file should not be modified in the way. 

@bjohare can you please take a look, and see why this format is breaking the platform?

**Comment by clash99** [comment] 2017-04-12 17:47
According to the [GPX 1.1 spec](http://www.topografix.com/GPX/1/1/#type_trksegType), a track with multiple track segments is a correct format.

**A Track Segment holds a list of Track Points which are logically connected in order. To represent a single GPS track where GPS reception was lost, or the GPS receiver was turned off, start a new Track Segment for each continuous span of track data.** 

If I upload the attached "broken" gpx file to a visualizer, I can see a path:

![screenshot 2017-04-12 12 45 47](https://cloud.githubusercontent.com/assets/1119621/24971552/07ac72bc-1f7e-11e7-9164-8327c2a2430f.png)

**Comment by SteadyCadence** [comment] 2017-04-13 15:08
Thanks @clash99.  It sounds to me like we need logic in Cadasta that connects the track segments if they are in track tags together.

**Comment by dpalomino** [comment] 2017-04-26 16:15
This should be fixed after releasing the import async process.

**Comment by dpalomino** [comment] 2017-04-26 16:19
Has to do with the specific format, @bjohare can you please take a look when you have a moment?

**Comment by SteadyCadence** [comment] 2017-06-02 08:25
I get no error or map layer when I upload this file in staging: 
[convertToGPX.txt](https://github.com/Cadasta/cadasta-platform/files/1047097/convertToGPX.txt)

I converted it from .gdb to .gpx in GPS Babel. Our partner in Thailand saves mostly in .gdb.... I think we will have to write a script to convert. It would be good to know what is accepted or not since the gpx doesnt seem to load.

**Comment by bjohare** [comment] 2017-06-02 09:00
@SteadyCadence .txt is not a gpx file so won't be recognized as a spatial resouce, it should be accepted as a Resource though which is probably why you're not getting an error message. Can you rename the file with a `.gpx` extension and try again?

**Comment by SteadyCadence** [comment] 2017-06-02 09:13
Sounds like it works with @bjohare's changes!  Awesome Sauce.

**Closed** 2017-06-13 17:17 UTC
Labels: bug, priority: medium
