### ISSUE TITLE
Server 500 Error when creating a new project....

### ISSUE THREAD

**Issue by fhpichel** [Cadasta/cadasta-platform#466] opened 2016-07-19 11:08 UTC
I'm getting an error when trying to create a new project...

![image](https://cloud.githubusercontent.com/assets/14877933/16947840/9d62f97e-4db1-11e6-884f-5e8cdcb4b730.png)

![image](https://cloud.githubusercontent.com/assets/14877933/16947849/aa0febb4-4db1-11e6-9c90-8ed131a34835.png)

**Comment by amplifi** [comment] 2016-07-19 11:15
Corresponding error in Django log: 

`Internal Server Error: /organizations/cadasta-foundation-demonstration/projects/new/
Traceback (most recent call last):
  File "/opt/cadasta/env/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: value too long for type character varying(50)`

**Comment by wonderchook** [comment] 2016-07-19 11:16
@fhpichel in the future can you provide more information about what you were doing in making the project. What data you put in and what you expect the output to be?

@amplifi this issue should be fixed in master. The issue is the text box allows 100 characters for the project name and the model only allows 50.

**Comment by amplifi** [comment] 2016-07-19 12:26
@wonderchook I was able to replicate this 500 error on staging. In searching for related updates, this PR was included in the last deployment to demo; I can confirm the code is present on all servers: https://github.com/Cadasta/cadasta-platform/commit/37f0c19e3bf8a1772a15891f21412300e49fba17

This open issue seems to be the same/similar: https://github.com/Cadasta/cadasta-platform/issues/414

**Comment by seav** [comment] 2016-07-19 12:49
Duplicate of #414

**Closed by seav** 2016-07-19 12:49 UTC
