### ISSUE TITLE
Possible to select "All Types" for relationship type

### ISSUE THREAD

**Issue by ian-ross** [Cadasta/cadasta-platform#588] opened 2016-08-23 14:38 UTC
When you create a relationship for a location, it's possible to select "All Types" from the relationship type dropdown list.  You then end up with a relationship with type "All Types".  Is this really right?  I would have thought that you need to select a specific relationship type.

(This is a result of https://github.com/Cadasta/cadasta-platform/blob/master/cadasta/party/models.py#L289.)

**Comment by seav** [comment] 2016-08-23 15:59
I'm not sure if this is the behavior since the very beginning, or if this is a regression. I saw the following screenshot before where "All Types" generates a required field error message but I don't know if this screenshot is a mockup or actual behavior that has now regressed:

![Screenshot](https://cloud.githubusercontent.com/assets/1119621/16840528/c7282de4-499a-11e6-800e-299bd4283bfb.png)

**Comment by wonderchook** [comment] 2016-08-23 16:53
@ian-ross which project are you seeing this in? I'm wondering if this is being caused by the XLSForm that is uploaded. I just made a new project without including a form and this isn't one of the options.

**Comment by wonderchook** [comment] 2016-08-23 16:56
Actually, sorry no looking in the wrong place. It would seem to me there wouldn't be a tenure type "All Types". @fhpichel and @nastynoel can you confirm this?

**Comment by nastynoel** [comment] 2016-08-23 21:43
Correct.

Can we take this opportunity to expand the list of possible relationship
and location types?

**Comment by wonderchook** [comment] 2016-08-25 18:44
@nastynoel please open a new ticket for that. 

I've marked this as a bug and we should fix it as we have time.

**Closed** 2016-08-31 22:43 UTC
Labels: bug, in progress, medium priority
