### ISSUE TITLE
Party detail page should have `can_edit` and `can_delete` checks

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1546] opened 2017-05-30 19:30 UTC
### Steps to reproduce the error
- Sign in with a Project User
- View a party detail page

### Actual behavior
![screen shot 2017-05-30 at 3 29 08 pm](https://cloud.githubusercontent.com/assets/8128188/26601167/df12b1be-454c-11e7-9f72-0e7b1f3b0c8d.png)

The edit and delete buttons appear in the top left corner

### Expected behavior
- Should match behavior on location detail page.

**Comment by linzjax** [comment] 2017-05-30 19:31
Same with the Relationship Detail page

**Comment by dpalomino** [comment] 2017-06-01 11:37
Thanks @bjohare, will take a look at the same time he is working on tutelary stuff.

**Comment by dpalomino** [comment] 2017-07-03 09:56
Hey @bjohare. Did you have a chance to take a look to this issue?

**Comment by bjohare** [comment] 2017-07-03 10:58
Not yet. Will look today.

**Comment by oliverroick** [comment] 2017-08-04 12:37
Duplicate of #1693. Closing

**Closed by oliverroick** 2017-08-04 12:37 UTC
Labels: bug, priority: medium
