### ISSUE TITLE
Resources tab visibility

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#409] opened 2016-07-12 17:40 UTC
The "Add from library" tab shouldn't be available if there are no resources in the library.  Only the option to "Upload" should be given.

**Comment by seav** [comment] 2016-07-21 09:58
Is this a duplicate of #295?

**Comment by ian-ross** [comment] 2016-07-21 10:03
Yes, it is.

**Closed by ian-ross** 2016-07-21 10:03 UTC
Labels: bug, medium priority, ui
