### ISSUE TITLE
Labels not displayed properly with multilanguage

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#645] opened 2016-09-05 17:16 UTC
### Steps to reproduce the error

(seen in demo)

1. Create a questionnaire with "label" and "label::OtherLanguage" columns. 
2. Use this in a project. 
3. Labels for locations, parties, etc *in the web interface* are not properly displayed (see screenshots) 
4. However in GeoODK is working fine and it's possible to swtich between languages
[Please try to describe the actions that led to the incorrect behavior
in as much detail as possible.]

PS: Not sure if this is a bug or something not supported by the platform....

![screen shot 2016-09-05 at 23 00 41](https://cloud.githubusercontent.com/assets/17198051/18254292/1bfaa462-73be-11e6-96b1-c6ace50d3d3d.png)
![screen shot 2016-09-05 at 23 04 06](https://cloud.githubusercontent.com/assets/17198051/18254298/2c5e0d80-73be-11e6-9ccd-fb1f800be05e.png)

**Comment by ian-ross** [comment] 2016-09-06 05:09
Duplicate of #389

**Closed by ian-ross** 2016-09-06 05:09 UTC
Labels: bug, ui/ux, xlsforms
