### ISSUE TITLE
Geometries/location attributes not loading in one project

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#1572] opened 2017-06-09 12:30 UTC
### Steps to reproduce the error

1. I have only seen this behaviour with [this project](https://platform.cadasta.org/organizations/landesa/projects/odisha-data-collection/)
2. Go to that project Overview page (8 locations)
3. See "Loading locations" message for ever

Other projects are working fine.

Log from the error [here](https://cadasta.slack.com/files/slackbot/F5R9JBFBL/spatial).

**Comment by SteadyCadence** [comment] 2017-06-09 13:33
There's a 500 error occurring on the spatial endpoint. I feel like its something in the attributes... needs investigation

**Comment by amplifi** [comment] 2017-08-08 12:24
If you look at the stacktrace for this error, you'll see one of the locations on this project has a blank `location_type`: https://opbeat.com/cadasta/platform-prod/errors/50/

We need to either disallow adding locations with a blank type, or allow locations to load successfully despite having a blank `location_type`.

**Comment by dpalomino** [comment] 2017-08-23 08:46
Thanks @amplifi for the analysis. I'd say it will be more flexible to allow locations without `location_type`, and cannot think in a reason for not allowing blank location_types. What do you think @SteadyCadence?

**Comment by oliverroick** [comment] 2018-02-15 11:15
There's only one location that is affected by this record across all of our instances. It's not possible to create a location without providing the type, so it's hard the reproduce the root cause of this error (i.e., why does this one location not have a `type`). 

The project is archived, so I'm assuming it's not being used. I updated the record, so `type` is set to `PA`, and the project will at least load. 

I'm closing the ticket; we can reopen if this issue resurfaces.

**Closed by oliverroick** 2018-02-15 11:15 UTC
Labels: bug, priority: medium
