### ISSUE TITLE
As a superuser, activating a user fails

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#927] opened 2016-11-11 09:20 UTC
### Steps to reproduce the error

On the development VM, with fixtures loaded:

1. Login as a superuser (either _iross_ or _oroick_)
2. Go to the user view (it's the link in the menu)
3. Active _testuser10_.
4. Logout
5. Login as _testuser10_

### Actual behavior

The account of _testuser10_ is still inactive.

### Expected behavior

The account of _testuser10_ is active. 

### The culprit 

`organization.views.default.UserActivation` sets the field `is_active` to the correct state; in the example above it is `True`. _testuser10_'s email verification period has expired; when they try to login, the account will be deactivated immediately. 

Should `organization.views.default.UserActivation` also set `email_verified` to `True` (i.e. manually confirming the email address) when activating the account?

**Comment by dpalomino** [comment] 2016-11-11 10:14
Thanks @oliverroick. IMO yes, it should also verify the account...

**Comment by seav** [comment] 2016-11-14 10:24
Can we actually say that the email is verified if it was never verified? The email could be wrong, for one thing. Maybe activating the user means just resetting the expiration period.

**Comment by oliverroick** [comment] 2016-11-15 08:27
I think, @seav is right. The user receives an email to confirm their email address, which will activate the account. 

The behaviour described above is correct, I think we can close this.

**Comment by amplifi** [comment] 2016-11-15 08:53
Does this cover the case where the user doesn't have an email address?

**Comment by wonderchook** [comment] 2016-11-15 09:17
Not sure that makes sense. We shouldn't be assuming people should be able to get emails. Long term I think the issue is we need to make an Architecture Design Proposal about how we deal with users without email addresses.

**Comment by dpalomino** [comment] 2016-11-30 17:08
Apart from the user without mail address registered (that's being discussed separately), this is now working as expected, so we can close the issue.

**Closed by dpalomino** 2016-11-30 17:08 UTC
Labels: bug, medium priority
