### ISSUE TITLE
geo_types not working fine with ODK in *some* Android devices

### ISSUE THREAD

**Issue by dpalomino** [Cadasta/cadasta-platform#641] opened 2016-09-04 17:38 UTC
### Steps to reproduce the error

We have seen this some Android devices during a training. In some of them (a bit less than 50%) the ODK app was not showing properly the geotypes questions, so instead of showing the "Record GeoShape", "Record GeoTrace", etc, it is showing just a text line to introduce the coordinates manually. 

Really weird, because in some of them ODK app was working fine, but others had this issue. 

Comments: 
- GPS was enabled and connectivity was ok
- Most of the devices were a bit old but not all of them (it happened with an Oppo Joy 3 and with a Galaxy S5)
- App updated to the last available version (1.4.10 (1061))

Tomorrow I will try to get some additional info (like Android version, screenshots etc). It seems to be a bug on ODK only affecting to some devices (or maybe Android versions?)

**Comment by wonderchook** [comment] 2016-09-06 18:55
Could you try installing GeoODK and see what happens?

**Comment by dpalomino** [comment] 2016-09-06 23:25
With GeoODK was working fine with all devices, but there are still some people that may prefer ODK over GeoODK (we recommend GeoODK).



Sent on move

**Comment by wonderchook** [comment] 2016-09-06 23:36
@dpalomino are you letting individual users choose in training or do you mean potential partners? I would not recommend letting individual users in a project choose and only use one. 

My other comment was about making sure they don't have other data collection apps installed based on ODK. I am able to reproduce the error by doing that on my own phone.

**Comment by dpalomino** [comment] 2016-09-07 07:13
Hi @wonderchook. We had plan to use ODK in training, because it was the partner's preference (surveyors were already using ODK and not GeoODK). Then we found that issue in some of the devices, but not in all of them. I was not able to found a pattern as it was appearing in old and new devices, with the last ODK version installed, etc. 

After seeing that was failing in some cases with ODK we switched to GeoODK and then there was no problem. 

On my own phone I have installed both ODK and GeoODK and it's working fine for me with both apps.

**Comment by wonderchook** [comment] 2016-09-07 20:11
The application I discovered that interferes is [Geo Data Collect](https://play.google.com/store/apps/details?id=hosm.odk.collect.android&hl=en). If I have it installed with ODK then the geotrace and the geoshape don't work. I believe this is because it is using an old version of ODK libraries. There are probably other applications using ODK as a base and have old libraries. You might want to check all the applications installed to see if there are any likely candidates that might be doing this.

**Comment by dpalomino** [comment] 2016-09-12 09:48
Thanks @wonderchook. I didn't see any other app, but I was unable to check in detail (the affected devices were not available later on). Maybe a recommendation for future sessions would be to deinstall all these other apps...

**Comment by wonderchook** [comment] 2016-09-12 22:56
@dpalomino I'm going to close this for the time being since we don't have a way to reproduce it. If we could reproduce it we'd need to report to the GeoODK developers.

**Closed by wonderchook** 2016-09-12 22:56 UTC
Labels: ui/ux, xlsforms

**Comment by dpalomino** [comment] 2016-09-14 05:03
ok, thanks @wonderchook. We will keep an eye on this and let you know if this happens again. Meanwhile we will recommend GeoODK instead of ODK...
