### ISSUE TITLE
PUT method for updating a project member produces Platform Error

### ISSUE THREAD

**Issue by bethschechter** [Cadasta/cadasta-platform#873] opened 2016-10-27 21:22 UTC
### Steps to reproduce the error

I was using the API UI to update a user. 

```
https://platform-staging-api.cadasta.org/api/v1/organizations/example-organization/projects/global-project/users/jane/
```

PATCH was not offered as a method, only PUT. 

![image](https://cloud.githubusercontent.com/assets/3361475/19785573/c3aef38a-9c4e-11e6-9827-fce945df532e.png)

When I tried to use PUT, I got the following platform error

![image](https://cloud.githubusercontent.com/assets/3361475/19785562/ade3c0a8-9c4e-11e6-9415-0cbd9da9725e.png)

### Actual behavior

See above

### Expected behavior

I'd expect that either (a) PATCH is offered as a choice, or that PUT does not create an error.

**Comment by oliverroick** [comment] 2016-10-28 13:54
I can't reproduce this exception; we might have fixed the root cause already. `PATCH` is offered under "Raw data" and it works when you provide `{"role": "PM"}`, for example. 

Closing this for now, feel free to re-open this issue when necessary.

**Closed by oliverroick** 2016-10-28 13:54 UTC
Labels: bug, medium priority
