### ISSUE TITLE
User messaging for anonymous users when browsing projects

### ISSUE THREAD

**Issue by nastynoel** [Cadasta/cadasta-platform#711] opened 2016-09-21 02:20 UTC
### Steps to reproduce the error

Open the demo or platform site as anonymous user and click on a project. 

I receive a congratulatory message about successfully creating a project and am presented with the option of creating a location. 

Although I am not then able to create a location, I should not be presented with this option in any case as an anonymous user browsing projects.

![image](https://cloud.githubusercontent.com/assets/14871114/18695512/b484a99c-7ff5-11e6-8d1a-320f8f0b95ed.png)

**Comment by ian-ross** [comment] 2016-09-21 05:25
Duplicate of #682.

**Closed by ian-ross** 2016-09-21 05:25 UTC
