### ISSUE TITLE
Review Map Zooms

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-platform#701] opened 2016-09-16 20:18 UTC
We currently don't keep track of what the user is looking at on the map when they switch actions. Sometimes this leads to jarring results. For example when the user zooms the overview map somewhere and then clicks add location. They have to rezoom to where they are. This ticket is for cataloging the actions and determining what they should be. 

@clash99 I think this is probably related to map improvements, but I think it makes sense to tackle them in pieces.

**Comment by clash99** [comment] 2017-03-15 19:20
Related to #718 and #1031. It will be in theory solved when upgrading django-leaflet (to be checked).

**Comment by clash99** [comment] 2017-03-15 19:23
Closing since this is a duplicate of #718.  Should be solved with SMAP.

**Closed by clash99** 2017-03-15 19:23 UTC
Labels: needs discussion
