### ISSUE TITLE
Attach resources : doc, docx files are not allowed

### ISSUE THREAD

**Issue by manoramahp** [Cadasta/cadasta-platform#1162] opened 2017-02-26 14:21 UTC
### Steps to reproduce the error

Go to project resources page
Click Attach -> Upload new
Browse a .doc file / .docx file

### Actual behavior

Below error message is shown
File type not allowed.

### Expected behavior

doc, docx files should be allowed. (According to the "Accepted file types")

**Comment by seav** [comment] 2017-02-26 20:13
Hi @manoramahp. I can't replicate this bug. Can you inform us what browser you are using and what OS?

**Comment by manoramahp** [comment] 2017-02-27 03:56
@seav I'm using Chrome browser on Ubuntu 16.04

**Comment by seav** [comment] 2017-02-27 13:13
I still can't reproduce this on the demo site. I encountered this error before too but in that case, the error was caused by a local setting in my browser/OS and it was not a problem with the Cadasta website. I think in your case, your Chrome or OS settings is not providing the correct MIME type for .doc or .docx files.

Can you go to [this page](http://codepen.io/anon/pen/BWNJxL?editors=1111), activate the file upload and select the document that you want to upload, and tell me what is displayed in the console? In my computer, using Firefox or Chrome in Linux shows "application/msword" for .doc files and "application/vnd.openxmlformats-officedocument.wordprocessingml.document" for .docx files. These are the correct MIME types for these files.

**Comment by manoramahp** [comment] 2017-02-28 08:26
@seav 
This is what I can see in the console "application/wps-office.docx". This issue might be because I'm using wps writer.

**Comment by seav** [comment] 2017-02-28 08:38
I see. So this is an OS issue. The Cadasta website checks for the MIME type of a file before it is accepted for uploading. In your case, the OS is providing a non-standard MIME type for your document. Let's leave this issue open for now and we in Cadasta will discuss if this is something we need to address, maybe in an FAQ. It's quite possible that other users may encounter a similar confusing error and they may not know how to fix it or apply a workaround.

**Comment by manoramahp** [comment] 2017-02-28 08:39
Thanks for looking into this @seav !

**Comment by dpalomino** [comment] 2017-02-28 16:24
Thanks @manoramahp, @seav. Is this something we can fix adding some filetypes as discussed in issue #1135?

**Comment by seav** [comment] 2017-03-01 02:50
@dpalomino: This is not related to the ODF file formats issue.

**Comment by SteadyCadence** [comment] 2017-05-31 05:10
I worked with Mabu and we successfully uploaded a .doc file.  Good thing that worked!  Otherwise we would have to convert all the files to PDF.

**Comment by dpalomino** [comment] 2017-06-12 10:06
Yeah @SteadyCadence. The issue was related to submitting files with non-standard MIME types (as we're checking this, if it's not a standard MIME type as Eugene explained then it's rejected). 

I think it's safe to close this issue for now, please reopen if needed.

**Closed by dpalomino** 2017-06-12 10:06 UTC
Labels: bug, priority: low
