### ISSUE TITLE
Master bug log for permissions feature branch

### ISSUE THREAD

**Issue by amplifi** [Cadasta/cadasta-platform#1739] opened 2017-08-23 14:40 UTC
Log any bugs identified for `feature/permissions` as comments on this issue. Related to #1667.

Cadasta permissions chart: https://docs.google.com/document/d/1RnjuWzjxkbnntJQHxo2Rbg8AiigkydtG7dLvFWZtAnU/edit?usp=sharing

**Comment by laura-barluzzi** [comment] 2017-08-23 20:48
Since I've addressed 3 similar bugs on permissions, I want to address here something I can confirm after I checked the staging of #1667.
1. The new permission feature provided by #1667  doesn't fix the root problem causing the 2 open issues #1680 and #1693. The following screenshots show how the user `proj1projectuser` (`Project User` role) is still able to see/click on edit and delete buttons when they shouldn't:
<img src="https://user-images.githubusercontent.com/16849118/29637288-86a59ad8-8808-11e7-91ea-e58873215b27.png" height="150"> <img src="https://user-images.githubusercontent.com/16849118/29637317-9b078f36-8808-11e7-9739-7cea8db19df6.png" height="150">

2. However, months ago I fixed an equivalent bug to #1680 and #1693 (see that closed issue here: #1233). The current staging code has that solution I made in [these lines](https://github.com/Cadasta/cadasta-platform/blob/ed38b6df1e680de73d4779ab94909e3ae5b9de28/cadasta/spatial/views/default.py#L118-L124) in `spacial/views/default.LocationDetail`. I am pleased to see that **my solution works just fine on staging**. The following screenshot shows how the user `proj1projectuser` (`Project User` role) cannot see the edit and delete buttons in the `spatial/location_detail.html` template:
<img src="https://user-images.githubusercontent.com/16849118/29637358-bddcca8a-8808-11e7-8d09-651bb24affbc.png" height="150">

3. This means that my proposed solution in the current PRs #1735 and #1738 (equal to the existing one in the code shared in point 2.) works with both permission features. This should make it easier to merge those bugfixes since we don't care about the effect it may have in the future if Cadasta switches to this new permission feature.

4. Last but not least, the approach proposed in PRs #1735 and #1738 can freely be used also in all the cases in which a `Project User` can see/click on buttons that leads to actions they don't have permission to do (e.g. add tenure relationship, detach, etc.). Here some screenshots showing some cases on staging of a Project User seeing and clicking on buttons leading to actions they actually cannot take:
<img src="https://user-images.githubusercontent.com/16849118/29637432-f5cf71b8-8808-11e7-9045-32eff5c4b3ac.png" height="150"> <img src="https://user-images.githubusercontent.com/16849118/29637487-182df36a-8809-11e7-9a84-99883e1647c5.png" height="150">

**Comment by amplifi** [comment] 2017-08-24 21:28
Needs: migration to map existing tutelary permissions to new permissions.

**Comment by clash99** [comment] 2017-08-25 15:45
### Organization Dashboard

1. A public user of an organization should not be able to view the sidebar or the members area on the dashboard.

![orgdashboard-publicuser](https://user-images.githubusercontent.com/1119621/29719876-88d1b19a-897d-11e7-9c7d-a4434354004e.png)

2. A project user (and up) of an organization should be able to view organization members. If you can see the "members" tab in the sidebar, you should be able to click on that tab and view the members index. Currently a project user sees a "don't have permission" message.

![orgdashboard-projectuser](https://user-images.githubusercontent.com/1119621/29720011-10f22780-897e-11e7-9751-0c67c7632412.png)

### Organization Member Page

1. A project user and data collector should be able to view the member index without having a link to the member detail page or an add button. 

![orgmembers-puanddc](https://user-images.githubusercontent.com/1119621/29721328-69eb47be-8982-11e7-92b4-43f8c78694f6.png)


2. A project manager and above should be able to view the member index with the link to the member detail page and an add button.

![orgmembers-projectmanager](https://user-images.githubusercontent.com/1119621/29720680-5326d54a-8980-11e7-8103-d9dde2683ac5.png)

**Comment by clash99** [comment] 2017-08-25 21:03
### Project Dashboard

1. A **data collector** should be able to add all project data (locations, parties, and resources), view team members, and view the project questionnaire.

![projdashboard-dc](https://user-images.githubusercontent.com/1119621/29732478-68318f60-89ae-11e7-9b47-5940fa5b8eae.png)

**Comment by oliverroick** [comment] 2017-11-13 10:28
This is not relevant anymore since the work has been restarted from scratch. Closing

**Closed by oliverroick** 2017-11-13 10:28 UTC
Labels: bug, permissions
