### ISSUE TITLE
Functional tests fail intermittently on Travis

### ISSUE THREAD

**Issue by oliverroick** [Cadasta/cadasta-platform#902] opened 2016-11-07 10:41 UTC
Some builds fail due to time out exceptions in functional tests. Different tests cause the exceptions, but they all seem to be related because the tests eventually all break in the same line. This needs further analysis; I'm collecting links to failed builds for the time being:

- https://travis-ci.org/Cadasta/cadasta-platform/jobs/172940515
- https://travis-ci.org/Cadasta/cadasta-platform/jobs/173842201

**Comment by seav** [comment] 2016-11-09 11:16
If I understand the errors correctly, I think this is caused by the alert box disappearing after a while which leads to the timeout because the tests are looking for the alert box's close button which has disappeared in the meantime. A similar issue was fixed by @ian-ross in PR #546 by changing the target element to be located from the close button to a unique element in the expected page.

**Comment by ian-ross** [comment] 2016-11-09 11:26
That's weird, because only "success" alerts are automatically dismissed after some time, and these cases are supposed to fail, i.e. to produce a persistent alert that needs to be explicitly dismissed by clicking on its close button.

**Comment by oliverroick** [comment] 2016-11-09 11:35
The exception is raised [here](https://github.com/Cadasta/cadasta-platform/blob/master/functional_tests/base.py#L149-L155)

```python
        try:
            WebDriverWait(self.browser, 10).until_not(
                EC.presence_of_element_located(wait)
            )
        except TimeoutException:
            self.get_screenshot('exception')
            raise
```

Doesn't that mean the exception is raised because the alter _is still_ present even though the close is clicked.

**Comment by ian-ross** [comment] 2016-11-09 11:37
Yeah, looks like it.  Don't know why clicking the button wouldn't make the alert go away though.

**Comment by amplifi** [comment] 2016-11-10 00:34
Decision from 9 Nov 2016 Dev Team call: temporary workaround - comment out functional tests causing intermittent failures, full solution target - Sprint 11.

**Comment by oliverroick** [comment] 2016-11-10 14:15
Can we close this in favour of #919 ?

**Comment by ian-ross** [comment] 2016-11-10 14:16
Yes: I was thinking we'd close this one once you'd disabled the failing tests.

**Closed by ian-ross** 2016-11-10 14:16 UTC
