### ISSUE TITLE
pip upgrade needs root

### ISSUE THREAD

**Issue by jimux** [Cadasta/cadasta-platform#971] opened 2016-12-06 13:24 UTC
### Steps to reproduce the error

I checked out the source tree and ran
vagrant up --provision

### Actual behavior

The VM build failed at step "Upgrade to latest PIP version":
  Installing collected packages: pip
  Found existing installation: pip 1.5.4
  Not uninstalling pip at /usr/lib/python2.7/dist-packages, owned by OS
  Can't roll back pip; was not uninstalled

### Expected behavior

"changed: [default]"

### Resolution

Rather than running as the app_user, vagrant, the update needs to be done as root.
become_user: "root"

**Comment by ian-ross** [comment] 2016-12-06 13:27
I think this is a duplicate of https://github.com/Cadasta/cadasta-platform/issues/900

**Comment by jimux** [comment] 2016-12-06 13:51
My mistake. I was only searching open issues when I checked. `pip install ansible==2.1.2.0` fixed it right up. Perhaps a note to that effect could be added to the README. Ansible 2.2 was also resulting in the "Install requirements" step looking for Python.h in the wrong place.

**Comment by ian-ross** [comment] 2016-12-06 13:55
Yeah, there's a bad bug in the `pip` module in Ansible 2.2 that more or less completely breaks conventional use of Python virtual environments.  There's an issue open for it so I hope it'll be fixed in the next Ansible release.

**Comment by dpalomino** [comment] 2017-02-24 11:37
Not relevant now, closing it.

**Closed by dpalomino** 2017-02-24 11:37 UTC
