### ISSUE TITLE
Permissions Issue: Project Users can submit questionnaires

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-platform#1036] opened 2017-01-09 16:47 UTC
### Steps to reproduce the error
1. Assign an org member project user permission on a project.
2. Login as that member in GeoODK Collect (or wherever you like)
3. Download the questionnaire, fill it out, submit it.

### Actual behavior
New data is submitted to the project

### Expected behavior
Step 3 and on should work if it is supposed to match the UI. When I'm logged in as the same user in the platform, I'm not allowed to add, edit, or delete anything, so I shouldn't be able to do so through questionnaires either?

**Comment by linzjax** [comment] 2017-01-09 16:55
Hm... So this is a little weird. 
1. you have permission
2. You downloaded the form
3. someone downgrades your permission so that you _no longer_ have permission to download questionnaires
4. if the original questionnaire is still on your device you can still submit data. 

However, if you have not yet downloaded the form, and your permissions are removed, you cannot download the form. Not sure how big of an issue this is.

**Comment by dpalomino** [comment] 2017-01-10 08:58
As @wonderchook confirmed, this issue is also happening when the user is removed from the organization. The problem seems to be that permissions are only checked when downloading the form from the apps, but not when submitting the forms to the platform. 

Moving to high-prioirty.

**Comment by oliverroick** [comment] 2017-01-10 11:31
We have individual permissions for each adding locations, relationships, parties and resources. On the platform we can check each of them individually.

When you upload data from GeoODK however, all record types are uploaded at once. How should we deal with this case — should we check if all actions are permitted? That means if a user can add locations, parties and relationships but no resources, the user will not be able to add anything from GeoODK.

**Comment by wonderchook** [comment] 2017-01-10 18:43
How do the import permissions work? I think it is less important to check each individual permission when someone is "bulk" uploading data.

**Closed** 2017-01-13 09:40 UTC
Labels: bug, priority: high
