### ISSUE TITLE
Logout doesn't appear to be working

### ISSUE THREAD

**Issue by clash99** [Cadasta/cadasta-platform#1227] opened 2017-03-07 16:26 UTC
### Steps to reproduce the error

In firefox and chrome, logout link from right user menu is only working sporadically.  

### Actual behavior

Logout link isn't logging me out.

### Expected behavior

Expect to be logged out and redirected to login page.

video:  https://screencast.com/t/uUX6camG85jw

**Comment by clash99** [comment] 2017-03-07 16:29
Seems to work once I've cleared my cache but wondering if others are having same issue.

**Comment by bjohare** [comment] 2017-03-07 16:32
Can confirm this using Chromium 53.0.

**Comment by amplifi** [comment] 2017-03-07 16:37
The logout issue just happened to me on a clean cache in Chrome 54.0.2840.98. Seems to occur from both https://platform-staging.cadasta.org/dashboard/ and https://platform-staging.cadasta.org/ entries.

**Comment by dpalomino** [comment] 2017-03-07 19:00
I've been testing a bit and have not been able to reproduce it. I've:

1.  logged in
2. navigate through a couple of projects
3. edit url manually and going to /dashboard or /
4. logged out

And works for me with Chrome and Firefox. Do we have a clear steps to reproduce?

**Comment by wonderchook** [comment] 2017-03-07 19:52
Do you have to be already logged in? I also could not reproduce, but I was not currently logged into staging.

**Comment by clash99** [comment] 2017-03-08 15:40
I confirmed that this was an issue again today where the logout link just redirected me to the dashboard again and again.  After clearing the cache it seemed to go away.

**Comment by bjohare** [comment] 2017-03-09 17:20
@dpalomino I haven't been able to reproduce this in the last two days. I suggest we close this and reopen if it reappears?

**Comment by dpalomino** [comment] 2017-03-14 15:33
Hi @bjohare. Yep, I agree. I haven't been able either. Please anyone reopen if reappears. 

Thanks :-)

**Closed by dpalomino** 2017-03-14 15:33 UTC
Labels: bug, needs investigation
